name: duelo_metabolico
description: "Plataforma de duelos de conhecimento para estudantes de nutrição"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  # UI e Design
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  
  # Gerenciamento de Estado
  provider: ^6.1.1
  
  # Navegação
  go_router: ^14.0.2
  
  # Persistência Local
  shared_preferences: ^2.2.2
  
  # Utilitários
  uuid: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: Oswald
      fonts:
        - asset: fonts/Oswald-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
          weight: 400
